# name: Deploy Laravel Project on push

# on:
#   push:
#     branches:
#       - ahmed-work

# jobs:
#   web-deploy:
#     name: Deploy via SSH
#     runs-on: ubuntu-latest

#     steps:
#     - name: Get the latest code
#       uses: actions/checkout@v2.3.2

#     - name: Setup Node.js environment
#       uses: actions/setup-node@master

#     - name: Install PHP dependencies
#       run: composer install --prefer-dist --no-scripts --no-dev --ignore-platform-reqs

#     - name: Install Node.js dependencies
#       run: npm install

#     - name: Build assets
#       run: npm run prod # or whatever script you use for compiling your assets

#     - name: Copy .env file and generate key
#       run: |
#         php -r "file_exists('.env') || copy('.env.example', '.env');"
#         php artisan key:generate

#     - name: Create storage symlink
#       run: php artisan storage:link
      
#     - name: Fix directory permissions
#       run: chmod -R 777 storage bootstrap/cache # Consider a more secure permission setting if possible

#     - name: Execute SSH Deployment Commands
#       uses: appleboy/ssh-action@master
#       with:
#         host: 141.136.33.98
#         username: u936501208
#         key: Panasonic93@
#         port: 65002 # Optional, if using a non-standard port
#         # host: ${{ secrets.SSH_HOST }}
#         # username: ${{ secrets.SSH_USERNAME }}
#         # key: ${{ secrets.SSH_PRIVATE_KEY }}
#         # port: ${{ secrets.SSH_PORT }} # Optional, if using a non-standard port
#         # You may add a passphrase if your SSH key is passphrase-protected:
#         # passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
#         script: |
#           cd /public_html/monezdev
#           git pull origin ahmed-work
#           composer install --no-dev
#           php artisan migrate
#           # Any other deployment steps like caching, restarting services, etc.
