name: Deploy Laravel Project on push
on:
  push:
    branches:
      - ahmed-work
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@master
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer update --ignore-platform-reqs
      - name: 🔨 Build Project
        run: |
          npm install  
      - name: Generate key
        run: php artisan key:generate
      - name: Generate storage link
        run: php artisan storage:link
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      # - name: 📂 Sync files
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      #   with:
      #     server: ftp.mi6.global
      #     username: u936501208.deploy
      #     password: ${{ secrets.ftp_password }}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          # host: ${{ secrets.HOST }}
          # username: ${{ secrets.USERNAME }}
          # password: ${{ secrets.PASSWORD }}
          # port: ${{ secrets.PORT }}
          host: 141.136.33.98
          username: u936501208
          password: Panasonic93@
          port: 65002
          script: whoami
          server-dir: /public_html/monezdev/
